Update gitleaks_slack.yml
ㅇㅇ

diff --git a/.github/workflows/gitleaks_slack.yml b/.github/workflows/gitleaks_slack.yml
--- a/.github/workflows/gitleaks_slack.yml
+++ b/.github/workflows/gitleaks_slack.yml
@@ -35,4 +35,6 @@ jobs:
 
       - name: Fail workflow if leaks found
         if: steps.gitleaks.outcome == 'failure'
-        run: exit 1
+        run: |
+          echo "🚫 Leak detected. Failing job..."
+          exit 1
